[build]
command = 'hugo --gc --minify -b $DEPLOY_PRIME_URL'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.148.2'
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
